export const packageName = "@oal/report";

export {
  DISPOSITIONS,
  DOCUMENTATION_OUTCOMES,
  EVIDENCE_INTEGRITY_FLAGS,
  PARTICIPANT_REPORT_STATUSES,
  REPORT_BUILDER_IDENTITY,
  REPORT_KIND,
  REPORT_LIFECYCLE_STAGES,
  REPORT_SCHEMA_VERSION,
  REPORT_WARNING_KINDS,
  TASK_OUTCOMES,
  CENSOR_CLASSES,
  isReport,
  type CensorClass,
  type CellProvenance,
  type ConfidenceInterval,
  type Disposition,
  type DocumentationOutcome,
  type EvidenceIntegrity,
  type EvidenceIntegrityCounts,
  type CensorClassCounts,
  type ReplacementCounts,
  type TaskOutcome,
  type TaskOutcomeCounts,
  type ParticipantReportStatus,
  type Report,
  type ReportBehavior,
  type ReportCounts,
  type ReportEstimate,
  type ReportLifecycleStage,
  type ReportMetric,
  type ReportProvenance,
  type ReportScope,
  type ReportSurfaces,
  type ReportWarning,
  type ReportWarningKind,
  type SafeId,
  type Sha256Hex,
  type ApiBehavior,
  type DocumentationBehavior,
  type SemanticBehavior,
  type SequenceVariant,
  type SensitivityEstimate,
  type UsageBehavior,
  type UsageDistribution,
  type MetricAvailability,
  type PerRunEvidenceLink,
  type FirstDiscoveryEntry,
  type ProbeChronologyEntry,
  type FinalStateEntry,
  type ReplacementLineageEntry,
  type ScheduleSummary,
  type ControlId
} from "./model.ts";
export {
  buildReport,
  buildTrialFacts,
  censorClassFor,
  reportSha256,
  reportStagesFor,
  resolveSlots,
  taskOutcomeFor,
  usageDistribution,
  type AssignmentTotals,
  type Denominators,
  type ProvenanceInput,
  type ReportBuildInput,
  type SlotResolution,
  type TrialFacts,
  type TrialFinalStateInput,
  type TrialInput,
  type TrialRow,
  type TrialUsageInput
} from "./aggregate.ts";
export {
  CHAIN_OF_THOUGHT_KEY_FRAGMENTS,
  MAX_SUMMARY_DEPTH,
  MAX_SUMMARY_ENTRIES,
  MAX_SUMMARY_TEXT_LENGTH,
  REDACTED_TEXT,
  TRUNCATION_MARKER,
  containsAnySecret,
  redactSummary,
  enforceReportRedaction,
  type SummaryRedactionContext
} from "./redact.ts";
export {
  DEFAULT_ALPHA,
  DEFAULT_FAMILY_ID,
  DEFAULT_LEVEL,
  comparePairedMetrics,
  compareReports,
  computeCompatibility,
  type CompareOptions,
  type MetricComparison,
  type MetricVerdict,
  type PairedMetricComparison,
  type PairedMetricInput,
  type RateSide,
  type ReportComparison
} from "./compare.ts";
export {
  REDACTED_MARKER,
  REPLAY_RESULT_KIND,
  REPLAY_SCHEMA_VERSION,
  VOLATILE_RESPONSE_HEADERS,
  replayContractSha256,
  replayRun,
  type ReplayClassification,
  type ReplayContract,
  type ReplayContractCheck,
  type ReplayCounts,
  type ReplayDiagnostic,
  type ReplayDiagnosticSeverity,
  type ReplayDifference,
  type ReplayDifferenceKind,
  type ReplayEvidenceEvent,
  type ReplayFixture,
  type ReplayInput,
  type ReplayLimits,
  type ReplayOutcome,
  type ReplayRequestStatus,
  type ReplayResult
} from "./replay.ts";
export {
  DOCTOR_CAPABILITIES,
  DOCTOR_PROBE_LIMITS,
  DOCTOR_REPORT_KIND,
  DOCTOR_REQUIRED_NODE_MAJOR,
  DOCTOR_SCHEMA_VERSION,
  aggregateDoctorReport,
  checkAdapter,
  checkDiskArtifacts,
  checkGatewayDeterminism,
  checkLimits,
  checkNodeRuntime,
  checkPackageVersions,
  checkSchemaFiles,
  checkSqliteStore,
  probeSqliteStore,
  runDoctor,
  type DoctorAdapter,
  type DoctorAdapterResult,
  type DoctorCapability,
  type DoctorCapabilityProbe,
  type DoctorCapabilityResult,
  type DoctorCheck,
  type DoctorDiskArtifact,
  type DoctorInput,
  type DoctorLimitTable,
  type DoctorLimitsInput,
  type DoctorReport,
  type DoctorSchemaFile,
  type DoctorStatus,
  type DoctorStoreResult
} from "./doctor.ts";
