export const packageName = "@oal/evidence";

export {
  Redactor,
  DEFAULT_KEY_PATTERNS,
  type RedactedValue,
  type RedactionConfig,
  type RedactorOptions
} from "./redaction.ts";
export {
  EventStream,
  JsonlSink,
  asJsonObject,
  captureBody,
  redactPath,
  traceHeaders,
  traceQuery,
  type BodyCaptureLimits,
  type BlobPutTarget,
  type CaptureBodyInput,
  type TraceBody,
  type TraceError,
  type TraceEvent,
  type TraceHeader,
  type TraceOperation,
  type TraceQueryParameter,
  type TraceValidationOutcome
} from "./trace.ts";
export {
  SemanticEventStream,
  documentationStream,
  type DocumentationExchange,
  type SemanticEvent
} from "./streams.ts";
export {
  ArtifactStore,
  EVIDENCE_COMPONENT,
  EVIDENCE_VERSION,
  MANIFEST_NAME,
  type ArtifactManifest,
  type BatchLayout,
  type ManifestEntry,
  type TrialLayout,
  type VerificationResult
} from "./artifacts.ts";
export { isCredentialShape } from "./redaction.ts";
export {
  LIFECYCLE_EVENT_TYPES,
  LIFECYCLE_EVIDENCE_SOURCES,
  LIFECYCLE_EVENT_ID_PREFIX,
  LIFECYCLE_INVALID_FIELD,
  LIFECYCLE_STAGES,
  LIFECYCLE_STREAM_NAME,
  MAX_DETAIL_ENTRIES,
  MAX_DETAIL_KEY_LENGTH,
  MAX_DETAIL_TEXT_LENGTH,
  MAX_TEXT_LENGTH,
  LifecycleStream,
  agentExited,
  agentSessionEvent,
  agentStarted,
  artifactFinalized,
  assignmentActivated,
  assignmentFinished,
  compilerDiagnostic,
  evaluatorCheck,
  evaluatorFinished,
  evaluatorStarted,
  isLifecycleEvent,
  lifecycleStage,
  mockStarted,
  mockStopped,
  processTerminated,
  resourceLimitReached,
  runCancelled,
  runCreated,
  runFinished,
  runStarted,
  sandboxDenial,
  stageRecord,
  studyAborted,
  studyFinished,
  type AgentSessionChannel,
  type ArtifactFinalizedPayload,
  type AssignmentActivatedPayload,
  type AssignmentFinishedPayload,
  type AgentExitedPayload,
  type AgentSessionEventPayload,
  type AgentStartedPayload,
  type CheckStatus,
  type CompilerDiagnosticPayload,
  type EvaluatorCheckPayload,
  type EvaluatorFinishedPayload,
  type EvaluatorStartedPayload,
  type EvidenceIntegrityFlag,
  type LifecycleDetailValue,
  type LifecycleDetails,
  type LifecycleEnvelope,
  type LifecycleEvent,
  type LifecycleEventDraft,
  type LifecycleEventRecord,
  type LifecycleEventType,
  type LifecycleEvidenceSource,
  type LifecycleObserved,
  type LifecyclePayloads,
  type LifecycleScope,
  type LifecycleStage,
  type LifecycleStagePayload,
  type LifecycleStageRecord,
  type MockStartedPayload,
  type MockStoppedPayload,
  type ProcessTerminatedPayload,
  type ResourceLimitName,
  type ResourceLimitReachedPayload,
  type RunCancelledPayload,
  type RunCreatedPayload,
  type RunFinishedPayload,
  type RunStartedPayload,
  type SandboxDenialPayload,
  type StudyAbortedPayload,
  type StudyFinishedPayload,
  type TerminalDisposition
} from "./lifecycle.ts";
export {
  METRICS_CARDINALITY_EXCEEDED,
  METRICS_INVALID_INCREMENT,
  METRICS_MISSING_LABEL,
  METRICS_UNKNOWN_LABEL,
  METRICS_UNKNOWN_LABEL_VALUE,
  METRICS_UNKNOWN_METRIC,
  METRICS_UNSAFE_LABEL,
  Metrics,
  type MetricCounter,
  type MetricLabels,
  type MetricsOptions,
  type MetricsSnapshot
} from "./metrics.ts";
export {
  CONTRADICTION_SIGNALS,
  classifyEvidenceIntegrity,
  integrityFlag,
  reasonForProblem,
  tailHealth,
  type ContradictionSignal,
  type EvidenceClassification,
  type IntegrityInput,
  type IntegrityReasonCode,
  type IntegrityResult,
  type TailHealthReport
} from "./integrity.ts";
